### PR TITLE
add new evaluator

### PR DESCRIPTION
**Pull request by leanNiki**
not sure about changes in pom.xml, but didnt work locally otherwise.

Created a new Evaluator, which sorts based on the minecraft creative inventory categories. Slightly tweaked to make more sense.
I know the implementation isn't the nicest with the 900 line List, but there seems to be no better option to get sensible organization. 
I'm also considering making it customizable in the config, but that would mean 900 lines of config,
however users could customize it fully to their liking.

### CODE REVIEW

**Comment by tom2208** [comment]
We should create a own util class for the creative tab, owning a list of Tab classes which are including the materials. 
Further should we use the Iteratable Interface to make interating through the list easier.

**Comment by leanNiki** [comment]
I realized you deleted your comment, but I still got the mail ^^
So let me explain my thoughts. I think one single list is still better than multiple lists/tabs for each category for following reasons:

- the sorting algorithm is really simple (just compare indexes)
- the items are not scattered around different files
  - duplicates are easier to find
  - sorting order is clear

However I think it would be really cool to have the list be configurable in game, and I believe the most usable option would probably to have a book and quill with the default list inside. But having a single book with 870 Lines is also not that ideal, since there can only be 14 lines per page. That would make it 62 pages long and there is also no search function. So it might make sense to split it up then, or add some custom book and quill item for the plugin. 

Thats a whole lot of work though. I'm currently working on making the list configurable in playerdata.yml, I'll add it to this pull request, hopefully today :)

**Comment by tom2208** [comment]
I would prefer a clearer, reusable and more adjustable way. For this we should rework the whole sorting system a bit. 
Creating filter objects you can combine for a sorting configuration. For instance CreariveTabFilter, ShapeFilter, AlphaticleFilter, etc.
The the server operators can set a combination of filters as the default state and the normal players can create their own filter combination. And we would just have to save some keywords in a list.

The rules of the combination could be:
A filter creates categories the next splits the categories into other sub categories (may include a not effected category, but should catrgorize all materials) etc.
Like: {CreativeTabFliter, ShapeFilter, AlphaticleFilter}
CreativeTabFilter => 10 CreativeTab categories 
=> each of this categories would call the next filter => creating new categories of the new filter 
A visualition would look a bit like the visualition of merge sort (https://en.wikipedia.org/wiki/File:Merge_sort_algorithm_diagram.svg).

Pros:
- easy to adjust, reuse
- easy to create new filters
- easy to safe the configuration of the players
- easy to save player configurations
- players can customize their own sortering 

Cons:
- you have to find abstraction levels to get the sorting you want, you can't just save a list of 900 Elements. You have to find the right combination of filters. 

By the way: the playerconfig.yml is for the individual playerdata, generell configurations are saved in the config.yml

**Comment by tom2208** [comment]
If you like to, i could create a new issue for that an assigned us.

**Comment by leanNiki** [comment]
Yes I think that would be cool. However I dont think we'll get around categorizing the materials by hand. There are some methods like, isBlock() isItem() isEdible() isOccluding() isFlammable() etc. but that is not nearly as fine grained as I'd like it. 

I realized to save the list in playerdata is unnecessary, as the players cant edit the file on the server. So I just added it to config.yml

Also, maybe you could create a Discord server, or something similar so we can talk and plan things out in a better way.

**Comment by tom2208** [comment]
"Also, maybe you could create a Discord server, or something similar so we can talk and plan things out in a better way." good idea. I will do this.

I will close this merge request without merging. Save the code i think we can reuse it in the new sorting system.

**Pull request closed without merging**
